//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.26 at 01:37:59 PM EET 
//


package com.glhf.imageprocessing.settings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pluginsDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "pluginsDirectory"
})
@XmlRootElement(name = "settings")
public class Settings {

    @XmlElement(required = true)
    protected String pluginsDirectory;

    /**
     * Gets the value of the pluginsDirectory property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPluginsDirectory() {
        return pluginsDirectory;
    }

    /**
     * Sets the value of the pluginsDirectory property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPluginsDirectory(String value) {
        this.pluginsDirectory = value;
    }

}
