//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.23 at 06:20:43 PM EET 
//


package com.glhf.imageprocessing.plugin.entity;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="accessClassName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="panelClassName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="optionList" type="{http://www.github.com/glhf}options" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "name",
        "accessClassName",
        "panelClassName",
        "optionList"
})
@XmlRootElement(name = "plugin")
public class Plugin {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String accessClassName;
    @XmlElement(required = true)
    protected String panelClassName;
    protected List<Options> optionList;

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the accessClassName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAccessClassName() {
        return accessClassName;
    }

    /**
     * Sets the value of the accessClassName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAccessClassName(String value) {
        this.accessClassName = value;
    }

    /**
     * Gets the value of the panelClassName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPanelClassName() {
        return panelClassName;
    }

    /**
     * Sets the value of the panelClassName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPanelClassName(String value) {
        this.panelClassName = value;
    }

    /**
     * Gets the value of the optionList property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the optionList property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptionList().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link Options }
     */
    public List<Options> getOptionList() {
        if (optionList == null) {
            optionList = new ArrayList<Options>();
        }
        return this.optionList;
    }

}
